use_frameworks!

platform :ios, '10.0'

target 'RemoteCooperationSDK_Example' do
  pod 'RemoteCooperationSDK', :path => '../'

  target 'RemoteCooperationSDK_Tests' do
    inherit! :search_paths

    
  end
end
