use_frameworks!

platform :ios, '10.0'

target 'RemoteCooperationSDK_Example' do
  
  pod 'RemoteCooperationSDK', :path => '../'
  
  # RTC
  pod 'RKRTC', :git => "https://github.com/RokidiOS/RKRTC", :branch => '3.2.1_swift5.7.1'
  pod 'RKCooperationCore', :git => "https://github.com/RokidiOS/RKCooperationCore", :branch => '3.2.1_swift5.7.1'
  
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
         config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
